---
- hosts: vagrant
  become: yes
  become_user: root
  vars:
    user: vagrant
    home_dir: /home/{{ user }}
    gitlab_hostname: localhost.localdomain
    gitlab_ip: 10.0.2.15
    gitlab_rb: /srv/gitlab/config/gitlab.rb

  tasks:
  - name: ensure docker is at the present version
    yum: name=docker state=present

  - name: enabled docker service
    service:
      name: docker
      enabled: yes

  - name: start docker service
    service:
      name: docker
      state: started

  - name: create data directory for gitlab
    file:
      path: /srv
      state: directory

  - name: allow docker to change files in the directory
    shell: "chcon -Rt svirt_sandbox_file_t /srv"
    changed_when: false

  - name: stop and remove exist docker containers
    shell: |
      containers=`docker ps -a -q`
      [ -z "$containers" ] || (docker stop $containers && docker rm $containers)
    changed_when: false

  - name: pull latest gitlab-ce image from repo
    shell: "docker pull gitlab/gitlab-ce:latest"
    changed_when: false

  - name: start gitlab container
    shell: |
      docker run --detach \
        --hostname {{ gitlab_hostname }} \
        --publish {{ gitlab_ip }}:443:443 \
        --publish {{ gitlab_ip }}:80:80 \
        --publish {{ gitlab_ip }}:12222:22 \
        --name gitlab \
        --restart always \
        --volume /srv/gitlab/config:/etc/gitlab \
        --volume /srv/gitlab/logs:/var/log/gitlab \
        --volume /srv/gitlab/data:/var/opt/gitlab \
        gitlab/gitlab-ce:latest
    changed_when: false

  - name: create selfsigned certificate
    shell: |
      mkdir -p /srv/gitlab/config/ssl/; cd /srv/gitlab/config/ssl/
      [ -e {{ gitlab_hostname }}.key ] && rm {{ gitlab_hostname }}.key
      [ -e {{ gitlab_hostname }}.crt ] && rm {{ gitlab_hostname }}.crt
      openssl ecparam -out {{ gitlab_hostname }}.key -name secp384r1 -genkey
      openssl req -new \
                  -x509 \
                  -key {{ gitlab_hostname }}.key \
                  -sha384 \
                  -days 3650 \
                  -subj "/CN={{ gitlab_hostname }}" \
                  -out {{ gitlab_hostname }}.crt
    changed_when: false

  - pause: seconds=60

  - name: make sure gitlab config is present at this moment
    shell: |
      [ -e {{ gitlab_rb }} ]
    register: chk_config
    changed_when: false
    failed_when: chk_config.rc not in [0, 1]

  - debug: var=chk_config.rc

  - name: update gitlab config(external_url)
    when: chk_config.rc == 0
    changed_when: false
    lineinfile: dest={{ gitlab_rb }}
                regexp="{{ item.regexp }}"
                insertafter="EOF"
                line="{{ item.line }}"
    with_items:
      - {
          regexp: '^external_url ',
          line: 'external_url \"https://{{ gitlab_hostname }}\"'
        }
      - {
          regexp: '^nginx\[''redirect_http_to_https''\] ',
          line: 'nginx[''redirect_http_to_https''] = true'
        }
      - {
          regexp: '^nginx\[''ssl_certificate''\] ',
          line: 'nginx[''ssl_certificate''] = \"/etc/gitlab/ssl/{{ gitlab_hostname }}.crt\"'
        }
      - {
          regexp: '^nginx\[''ssl_certificate_key''\] ',
          line: 'nginx[''ssl_certificate_key''] = \"/etc/gitlab/ssl/{{ gitlab_hostname }}.key\"'
        }
      - {
          regexp: '^nginx\[''ssl_ciphers''\] ',
          line: 'nginx[''ssl_ciphers''] = \"ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256\"'
        }
      - {
          regexp: '^nginx\[''ssl_prefer_server_ciphers''\] ',
          line: 'nginx[''ssl_prefer_server_ciphers''] = \"on\"'
        }
      - {
          regexp: '^nginx\[''ssl_protocols''\] ',
          line: 'nginx[''ssl_protocols''] = \"TLSv1.2\"'
        }

  - name: restart gitlab
    when: chk_config.rc == 0
    changed_when: false
    shell: "docker restart gitlab"
