---
- hosts: vagrant
  user: vagrant
  vars:
    user: vagrant
    home_dir: /home/{{ user }}
    gitlab_hostname: localhost.localdomain
    gitlab_ip: 10.0.2.15
    gitlab_rb: /srv/gitlab/config/gitlab.rb

  tasks:
  - name: ensure docker is at the present version
    sudo: yes
    yum: name=docker state=present

  - name: enabled docker service
    sudo: yes
    service:
      name: docker
      enabled: yes

  - name: start docker service
    sudo: yes
    service:
      name: docker
      state: started

  - name: create data directory for gitlab
    sudo: yes
    file:
      path: /srv
      state: directory

  - name: allow docker to change files in the directory
    sudo: yes
    shell: "chcon -Rt svirt_sandbox_file_t /srv"
    changed_when: false

  - name: stop and remove exist docker containers
    sudo: yes
    shell: |
      containers=`docker ps -a -q`
      [ -z "$containers" ] || (docker stop $containers && docker rm $containers)
    changed_when: false

  - name: pull latest gitlab-ce image from repo
    sudo: yes
    shell: "docker pull gitlab/gitlab-ce:latest"
    changed_when: false

  - name: start gitlab container
    sudo: yes
    shell: |
      docker run --detach \
        --hostname {{ gitlab_hostname }} \
        --publish {{ gitlab_ip }}:443:443 \
        --publish {{ gitlab_ip }}:80:80 \
        --publish {{ gitlab_ip }}:12222:22 \
        --name gitlab \
        --restart always \
        --volume /srv/gitlab/config:/etc/gitlab \
        --volume /srv/gitlab/logs:/var/log/gitlab \
        --volume /srv/gitlab/data:/var/opt/gitlab \
        gitlab/gitlab-ce:latest
    changed_when: false

  - name: create selfsigned certificate
    sudo: yes
    shell: |
      mkdir -p /srv/gitlab/config/ssl/; cd /srv/gitlab/config/ssl/
      [ -e {{ gitlab_hostname }}.key ] && rm {{ gitlab_hostname }}.key
      [ -e {{ gitlab_hostname }}.crt ] && rm {{ gitlab_hostname }}.crt
      openssl ecparam -out {{ gitlab_hostname }}.key -name secp384r1 -genkey
      openssl req -new \
                  -x509 \
                  -key {{ gitlab_hostname }}.key \
                  -sha384 \
                  -days 3650 \
                  -subj "/CN={{ gitlab_hostname }}" \
                  -out {{ gitlab_hostname }}.crt
    changed_when: false

  - pause: seconds=60

  - name: make sure gitlab config is present at this moment
    sudo: yes
    shell: |
      [ -e {{ gitlab_rb }} ]
    register: chk_config
    changed_when: false
    failed_when: chk_config.rc not in [0, 1]

  - debug: var=chk_config.rc

  - name: update gitlab config(external_url)
    when: chk_config.rc == 0
    sudo: yes
    changed_when: false
    lineinfile: >
      dest={{ gitlab_rb }}
      regexp="^external_url "
      insertafter="EOF"
      line="external_url 'https://{{ gitlab_hostname }}'"
  - name: update gitlab config(nginx['redirect_http_to_https'])
    when: chk_config.rc == 0
    sudo: yes
    changed_when: false
    lineinfile: >
      dest={{ gitlab_rb }}
      regexp="^nginx\['redirect_http_to_https'\] "
      insertafter="EOF"
      line="nginx['redirect_http_to_https'] = true"
  - name: update gitlab config(nginx['ssl_certificate'])
    when: chk_config.rc == 0
    sudo: yes
    changed_when: false
    lineinfile: >
      dest={{ gitlab_rb }}
      regexp="^nginx\['ssl_certificate'\] "
      insertafter="EOF"
      line="nginx['ssl_certificate'] = '/etc/gitlab/ssl/{{ gitlab_hostname }}.crt'"
  - name: update gitlab config(nginx['ssl_certificate_key'])
    when: chk_config.rc == 0
    sudo: yes
    changed_when: false
    lineinfile: >
      dest={{ gitlab_rb }}
      regexp="^nginx\['ssl_certificate_key'\] "
      insertafter="EOF"
      line="nginx['ssl_certificate_key'] = '/etc/gitlab/ssl/{{ gitlab_hostname }}.key'"
  - name: update gitlab config(nginx['ssl_ciphers'])
    when: chk_config.rc == 0
    sudo: yes
    changed_when: false
    lineinfile: >
      dest={{ gitlab_rb }}
      regexp="^nginx\['ssl_ciphers'\] "
      insertafter="EOF"
      line="nginx['ssl_ciphers'] = 'ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256'"
  - name: update gitlab config(nginx['ssl_prefer_server_ciphers'])
    when: chk_config.rc == 0
    sudo: yes
    changed_when: false
    lineinfile: >
      dest={{ gitlab_rb }}
      regexp="^nginx\['ssl_prefer_server_ciphers'\] "
      insertafter="EOF"
      line="nginx['ssl_prefer_server_ciphers'] = 'on'"
  - name: update gitlab config(nginx['ssl_protocols'])
    when: chk_config.rc == 0
    sudo: yes
    changed_when: false
    lineinfile: >
      dest={{ gitlab_rb }}
      regexp="^nginx\['ssl_protocols'\] "
      insertafter="EOF"
      line="nginx['ssl_protocols'] = 'TLSv1.2'"

  - name: restart gitlab
    when: chk_config.rc == 0
    sudo: yes
    changed_when: false
    shell: "docker restart gitlab"
