---
- hosts: vagrant
  vars:
    user: vagrant
    home_dir: /home/{{ user }}

  tasks:
  - name: update to latest
    become: yes
    become_user: root
    yum: name=* state=latest

  - name: ensure epel repo is at the latest version
    become: yes
    become_user: root
    yum: name="epel-release" state=latest

  - name: ensure Development tools are at the latest version
    become: yes
    become_user: root
    yum: name="@Development tools" state=latest

  - name: ensure items are in the present version
    become: yes
    become_user: root
    yum: name="{{ item.name }}"
         state=present
    with_items:
      - { name: 'sl' }
      - { name: 'git' }
      - { name: 'openssl-devel' }
      - { name: 'libyaml-devel' }
      - { name: 'readline-devel' }
      - { name: 'sqlite-devel' }
      - { name: 'xz-devel' }
      - { name: 'pcre-devel' }
      - { name: 'zsh' }
      - { name: 'tmux' }
      - { name: 'vim' }
      - { name: 'curl' }
      - { name: 'wget' }
      - { name: 'tree' }
      - { name: 'golang' }
      - { name: 'ansible' }
      - { name: 'docker' }
      - { name: 'the_silver_searcher' }
      - { name: 'jq' }
      - { name: 'ngrep' }
      - { name: 'nmap' }
      - { name: 'socat' }

  - name: ensure login shell is zsh
    become: yes
    become_user: root
    changed_when: false
    command: grep {{ user }} /etc/passwd
    register: currentshell
  - name: change login shell to zsh
    become: yes
    become_user: root
    when: currentshell.stdout.find('/bin/zsh') == -1
    command: chsh -s /bin/zsh {{ user }}

  - name: get oh-my-zsh(https://github.com/robbyrussell/oh-my-zsh)
    git: repo=https://github.com/robbyrussell/oh-my-zsh.git
         dest={{ home_dir }}/.oh-my-zsh
         force=yes
  - name: copy .zshrc from oh-my-zsh template
    changed_when: false
    shell: |
      mv {{ home_dir }}/.zshrc {{ home_dir }}/.zshrc.org
      cp {{ home_dir }}/.oh-my-zsh/templates/zshrc.zsh-template {{ home_dir }}/.zshrc.0

  - name: copy zshrc fragment file from templates
    changed_when: false
    template: src=templates/zshrc.j2 dest={{ home_dir }}/.zshrc.1

  - name: mearge zshrc with fragments
    changed_when: false
    assemble: src={{ home_dir }} dest={{ home_dir }}/.zshrc regexp='\.zshrc\.[0-9]'

  - name: update zshrc
    changed_when: false
    lineinfile: dest={{ home_dir }}/.zshrc regexp=^ZSH_THEME= line='ZSH_THEME=\"sunrise\"'

  - name: remove fragment files
    changed_when: false
    command: rm {{ home_dir }}/.zshrc.0 {{ home_dir }}/.zshrc.1

  - name: get autojump(https://github.com/joelthelion/autojump)
    git: repo=https://github.com/joelthelion/autojump.git
         dest=/var/tmp/autojump
  - name: install autojump to home
    shell: |
      creates={{ home_dir }}/.autojump/bin/autojump
      cd /var/tmp/autojump
      ./install.py

  - name: get nodebrew(https://github.com/hokaccha/nodebrew)
    get_url: url=http://git.io/nodebrew
             dest=/var/tmp/nodebrew
  - name: install nodebrew
    changed_when: false
    shell: |
      cd /var/tmp
      perl nodebrew setup

  - name: get rbenv(https://github.com/sstephenson/rbenv)
    git: repo=https://github.com/sstephenson/rbenv.git
         dest={{ home_dir }}/.rbenv
  - name: get ruby-build(https://github.com/sstephenson/ruby-build)
    git: repo=https://github.com/sstephenson/ruby-build.git
         dest={{ home_dir }}/.rbenv/plugins/ruby-build

  - name: install peco(https://github.com/peco/peco) to home
    changed_when: false
    shell: |
      mkdir ~/.go
      export GOPATH="$HOME/.go"
      go get github.com/peco/peco/cmd/peco
      go get github.com/peco/migemogrep

  - name: set git config
    changed_when: false
    shell: |
      git config --global core.editor vim
      git config --global alias.l 'log --graph --name-status --pretty=format:"%C(red)%h %C(green)%an %Creset%s %C(yellow)%d%Creset"'
      git config --global color.ui auto

  - name: put .vimrc to home
    template: src=templates/vimrc.j2 dest={{ home_dir }}/.vimrc

  - name: put .tmux.conf to home
    template: src=templates/tmux_conf.j2 dest={{ home_dir }}/.tmux.conf

  - name: create peco config dir to home
    changed_when: false
    shell: |
      [ -e {{ home_dir }}/.peco ] || mkdir {{ home_dir }}/.peco
  - name: put peco config to home
    template: src=templates/peco_config.j2 dest={{ home_dir }}/.peco/config.json
